In [3]:
import numpy as np

In [5]:
populasyon = np.random.randint(0,80,1000)

In [7]:
populasyon

array([72, 47, 26,  6, 74, 14, 46, 39, 14, 49, 43, 23,  9, 73, 64, 20, 45,
       28, 50, 71, 44,  4,  1, 24, 26,  4,  1, 16, 19, 37, 69, 41,  7, 53,
       52, 48, 62, 44, 26, 55, 40, 17, 61, 29, 54, 28, 23, 64, 77,  2, 39,
       36, 27, 47, 11, 47, 57, 52, 74, 34, 35, 18, 25,  0, 44,  0, 34, 32,
       26, 33, 66, 46, 16, 24,  9, 44, 74, 17, 64, 15, 38, 75, 13, 62, 15,
       52, 15, 57, 35, 28, 72, 59, 28,  3, 76, 26, 15, 59, 41, 76, 52, 63,
       17, 59, 20, 68, 19, 70,  7, 28, 69,  2, 22, 25, 59, 67, 42, 14, 43,
       70, 51, 27, 11, 34, 49, 43, 76,  3, 56,  9, 62, 37, 33, 56, 27, 10,
       74, 70, 59, 57, 21, 67, 56, 27,  7, 78, 37, 17, 50, 37, 68, 63, 36,
       56, 34, 58, 57,  7, 49, 55, 38, 58, 26, 19, 33, 54, 33,  8, 41, 10,
       56, 53, 72,  7,  4,  0, 20, 49, 33, 63, 77, 70, 74, 63, 67,  4, 31,
       46, 78, 26, 56, 51, 37, 16, 53, 42, 12, 67, 51, 40, 11, 73, 68, 17,
       73, 62, 73,  4, 57, 32, 73, 24, 63, 46, 37, 42, 64, 55, 17,  8, 43,
       73, 13, 76, 46, 66

In [17]:
#gözlem için
populasyon[0:10]

array([72, 47, 26,  6, 74, 14, 46, 39, 14, 49])

In [11]:
#örneklem çekimi 
np.random.seed(10)
# seed = aynı yapıya göre örnek çekmesi için 
orneklem = np.random.choice(a=populasyon, size =100)

In [13]:
orneklem

array([ 2, 43,  5, 35, 59, 30, 34, 57, 45, 41, 47, 21, 26, 14, 24, 28, 56,
       40, 58, 45, 50, 42, 44, 12, 74, 11, 11, 37, 11, 66,  8, 11, 60, 27,
       54, 70, 11, 17, 35, 73, 10, 61, 48, 73, 67, 74, 55, 18, 28,  5, 26,
        7, 32,  4, 45, 55,  3, 17,  9, 51, 55, 16, 74, 71,  9, 64, 42, 20,
       55,  5, 24, 46, 11, 74, 18, 61, 10, 73, 67, 67, 13, 31, 33, 31, 54,
       51, 74, 46, 11, 70,  4, 13, 74, 67, 78, 19, 72, 70,  7, 27])

In [19]:
orneklem[0:10]

array([ 2, 43,  5, 35, 59, 30, 34, 57, 45, 41])

In [21]:
orneklem.mean()

38.29

In [25]:
populasyon.mean()

39.34

##### işte sonuç çok yakın daha küçük bir veriseti ile aynı değere yaklaşabiliyoruz


### Örneklem Dağılımı

In [31]:
orneklem1 = np.random.choice(a=populasyon, size =100)
orneklem2 = np.random.choice(a=populasyon, size =100)
orneklem3 = np.random.choice(a=populasyon, size =100)
orneklem4 = np.random.choice(a=populasyon, size =100)
orneklem5 = np.random.choice(a=populasyon, size =100)
orneklem6 = np.random.choice(a=populasyon, size =100)
orneklem7 = np.random.choice(a=populasyon, size =100)
orneklem8 = np.random.choice(a=populasyon, size =100)
orneklem9 = np.random.choice(a=populasyon, size =100)
orneklem10 = np.random.choice(a=populasyon, size =100)

In [37]:
(orneklem1.mean() + orneklem2.mean() + orneklem3.mean() + orneklem4.mean() + orneklem5.mean() + orneklem6.mean() + orneklem7.mean() + orneklem8.mean() + orneklem9.mean() + orneklem10.mean()) / 10

39.291999999999994

##### daha fazla örnek ile kitleye daha yakın bir sonuç alabiliyoruz